# Generated by Django 4.0.4 on 2022-04-16 21:28

from django.db import migrations, models
import django.db.models.deletion
import pages.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('email_id', models.EmailField(max_length=256, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=pages.models.employee_photo_upload)),
                ('salary', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(max_length=200)),
                ('leave_type', models.CharField(choices=[('CASUAL', 'CASUAL'), ('SICK', 'SICK'), ('PRIVILEGE', 'PRIVILEGE')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SIBLING', 'SIBLING'), ('SON', 'SON')], max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email_id', models.EmailField(blank=True, max_length=256, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.profile')),
            ],
        ),
    ]
